slick.dbs.default.profile = "slick.jdbc.PostgresProfile$"

slick.dbs.default.db {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/transaction_engine"
  user = "postgres"
  password = "21125aaJV"
  connectionPool = "HikariCP"
  keepAliveConnection = true
}

# Flyway config
flyway.url = "jdbc:postgresql://localhost:5432/transaction_engine"
flyway.user = "postgres"
flyway.password = "21125aaJV"
flyway.locations = "classpath:db/migration"

#  Enable your module here
play.modules.enabled += "modules.DatabaseModule"