slick.dbs.default.profile = "slick.jdbc.PostgresProfile$"
slick.dbs.default.db {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/mydb"
  user = "postgres"
  password = "password"
  connectionPool = HikariCP
  keepAliveConnection = true
}

# Flyway config
flyway.url=jdbc:postgresql://localhost:5432/mydb
flyway.user=postgres
flyway.password=password
flyway.locations=filesystem:db/migration